In [1]:
import warnings; warnings.filterwarnings('ignore')

import pandas, seaborn as sns

import matplotlib.pyplot as plt

salesurl = '/content/train.csv'

In [2]:
sales = pandas.read_table(salesurl, sep=',')

sales.shape

(9653, 17)

In [3]:
sales.iloc[:5, :9]

,order_id,order_date,ship_date,ship_mode,customer_id,customer_name,segment,country,city
0,CA-2017-152156,08/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson
1,CA-2017-152156,08/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson
2,CA-2017-138688,12/06/2017,16/06/2017,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles
3,US-2016-108966,11/10/2016,18/10/2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale
4,US-2016-108966,11/10/2016,18/10/2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale

In [4]:
sales.iloc[:5, 9:]

,state,postal_code,region,product_id,category,sub_category,product_name,sales
0,Kentucky,42420.0,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600
1,Kentucky,42420.0,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400
2,California,90036.0,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200
3,Florida,33311.0,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775
4,Florida,33311.0,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680

Melakukan Inspeksi Apakah Kolom Tanggal Order & Tanggal Pengiriman Sudah Tipe Data Date

In [5]:
sales.order_date.dtype

dtype('O')

In [6]:
sales['order_date'] = pandas.to_datetime(sales['order_date'], format = '%d/%m/%Y', errors = 'coerce')

sales.order_date.dtype

dtype('<M8[ns]')

In [7]:
sales.ship_date.dtype

dtype('O')

In [8]:
sales['ship_date'] = pandas.to_datetime(sales['ship_date'], format = '%d/%m/%Y', errors = 'coerce')

sales.ship_date.dtype

dtype('<M8[ns]')

Melakuka Inspeksi Pada Kolom Sales

In [9]:
sales.sales.dtype

dtype('float64')

In [10]:
float(sales.sales.sum())

2225138.9235

*Total Penjualan Kumulatif Sejauh ini Adalah : $ 2.225.138,92*